import "@testing-library/jest-dom";
import { render, screen, waitFor } from "@testing-library/react";
import { rest, server } from "../../scaffold/server";
import PlayersStatsTable from "./PlayerStatsTable";

const mockedPlayerId = 565;

const mockedPlayerStats = [
  {
    id: 15842,
    ast: 2,
    blk: 0,
    dreb: 2,
    fg3_pct: null,
    fg3a: 0,
    fg3m: 0,
    fg_pct: 0.143,
    fga: 7,
    fgm: 1,
    ft_pct: null,
    fta: 0,
    ftm: 0,
    game: {
      id: 630,
      date: "1990-11-02T00:00:00.000Z",
      home_team_id: 1,
      home_team_score: 115,
      period: 4,
      postseason: false,
      season: 1990,
      status: "Final",
      time: " ",
      visitor_team_id: 22,
      visitor_team_score: 111,
    },
    min: "12",
    oreb: 0,
    pf: 1,
    player: {
      id: 565,
      first_name: "John",
      height_feet: null,
      height_inches: null,
      last_name: "Battle",
      position: "",
      team_id: 1,
      weight_pounds: null,
    },
    pts: 2,
    reb: 2,
    stl: 0,
    team: {
      id: 1,
      abbreviation: "ATL",
      city: "Atlanta",
      conference: "East",
      division: "Southeast",
      full_name: "Atlanta Hawks",
      name: "Hawks",
    },
    turnover: 0,
  },
  {
    id: 16183,
    ast: 2,
    blk: 0,
    dreb: 1,
    fg3_pct: null,
    fg3a: 0,
    fg3m: 0,
    fg_pct: 0.6,
    fga: 5,
    fgm: 3,
    ft_pct: 0.727,
    fta: 11,
    ftm: 8,
    game: {
      id: 644,
      date: "1990-11-03T00:00:00.000Z",
      home_team_id: 1,
      home_team_score: 121,
      period: 4,
      postseason: false,
      season: 1990,
      status: "Final",
      time: " ",
      visitor_team_id: 12,
      visitor_team_score: 120,
    },
    min: "22",
    oreb: 0,
    pf: 5,
    player: {
      id: 565,
      first_name: "John",
      height_feet: null,
      height_inches: null,
      last_name: "Battle",
      position: "",
      team_id: 1,
      weight_pounds: null,
    },
    pts: 14,
    reb: 1,
    stl: 2,
    team: {
      id: 1,
      abbreviation: "ATL",
      city: "Atlanta",
      conference: "East",
      division: "Southeast",
      full_name: "Atlanta Hawks",
      name: "Hawks",
    },
    turnover: 2,
  },
  {
    id: 16463,
    ast: 0,
    blk: 0,
    dreb: 1,
    fg3_pct: null,
    fg3a: 0,
    fg3m: 0,
    fg_pct: 0.333,
    fga: 3,
    fgm: 1,
    ft_pct: 1,
    fta: 1,
    ftm: 1,
    game: {
      id: 658,
      date: "1990-11-06T00:00:00.000Z",
      home_team_id: 26,
      home_team_score: 85,
      period: 4,
      postseason: false,
      season: 1990,
      status: "Final",
      time: " ",
      visitor_team_id: 1,
      visitor_team_score: 102,
    },
    min: "11",
    oreb: 0,
    pf: 1,
    player: {
      id: 565,
      first_name: "John",
      height_feet: null,
      height_inches: null,
      last_name: "Battle",
      position: "",
      team_id: 1,
      weight_pounds: null,
    },
    pts: 3,
    reb: 1,
    stl: 0,
    team: {
      id: 1,
      abbreviation: "ATL",
      city: "Atlanta",
      conference: "East",
      division: "Southeast",
      full_name: "Atlanta Hawks",
      name: "Hawks",
    },
    turnover: 1,
  },
  {
    id: 16882,
    ast: 2,
    blk: 1,
    dreb: 2,
    fg3_pct: 0,
    fg3a: 1,
    fg3m: 0,
    fg_pct: 0.6,
    fga: 10,
    fgm: 6,
    ft_pct: 0.75,
    fta: 4,
    ftm: 3,
    game: {
      id: 679,
      date: "1990-11-09T00:00:00.000Z",
      home_team_id: 10,
      home_team_score: 143,
      period: 4,
      postseason: false,
      season: 1990,
      status: "Final",
      time: " ",
      visitor_team_id: 1,
      visitor_team_score: 128,
    },
    min: "30",
    oreb: 0,
    pf: 1,
    player: {
      id: 565,
      first_name: "John",
      height_feet: null,
      height_inches: null,
      last_name: "Battle",
      position: "",
      team_id: 1,
      weight_pounds: null,
    },
    pts: 15,
    reb: 2,
    stl: 0,
    team: {
      id: 1,
      abbreviation: "ATL",
      city: "Atlanta",
      conference: "East",
      division: "Southeast",
      full_name: "Atlanta Hawks",
      name: "Hawks",
    },
    turnover: 4,
  },
  {
    id: 16984,
    ast: 0,
    blk: 0,
    dreb: 0,
    fg3_pct: null,
    fg3a: 0,
    fg3m: 0,
    fg_pct: 0.333,
    fga: 6,
    fgm: 2,
    ft_pct: null,
    fta: 0,
    ftm: 0,
    game: {
      id: 702,
      date: "1990-11-10T00:00:00.000Z",
      home_team_id: 13,
      home_team_score: 94,
      period: 4,
      postseason: false,
      season: 1990,
      status: "Final",
      time: " ",
      visitor_team_id: 1,
      visitor_team_score: 112,
    },
    min: "15",
    oreb: 0,
    pf: 0,
    player: {
      id: 565,
      first_name: "John",
      height_feet: null,
      height_inches: null,
      last_name: "Battle",
      position: "",
      team_id: 1,
      weight_pounds: null,
    },
    pts: 4,
    reb: 0,
    stl: 1,
    team: {
      id: 1,
      abbreviation: "ATL",
      city: "Atlanta",
      conference: "East",
      division: "Southeast",
      full_name: "Atlanta Hawks",
      name: "Hawks",
    },
    turnover: 0,
  },
  {
    id: 17330,
    ast: 3,
    blk: 1,
    dreb: 2,
    fg3_pct: 0,
    fg3a: 1,
    fg3m: 0,
    fg_pct: 0.615,
    fga: 13,
    fgm: 8,
    ft_pct: 0.667,
    fta: 3,
    ftm: 2,
    game: {
      id: 694,
      date: "1990-11-13T00:00:00.000Z",
      home_team_id: 1,
      home_team_score: 104,
      period: 4,
      postseason: false,
      season: 1990,
      status: "Final",
      time: " ",
      visitor_team_id: 6,
      visitor_team_score: 121,
    },
    min: "23",
    oreb: 1,
    pf: 3,
    player: {
      id: 565,
      first_name: "John",
      height_feet: null,
      height_inches: null,
      last_name: "Battle",
      position: "",
      team_id: 1,
      weight_pounds: null,
    },
    pts: 18,
    reb: 3,
    stl: 1,
    team: {
      id: 1,
      abbreviation: "ATL",
      city: "Atlanta",
      conference: "East",
      division: "Southeast",
      full_name: "Atlanta Hawks",
      name: "Hawks",
    },
    turnover: 1,
  },
  {
    id: 17485,
    ast: 5,
    blk: 0,
    dreb: 1,
    fg3_pct: 1,
    fg3a: 1,
    fg3m: 1,
    fg_pct: 0.455,
    fga: 11,
    fgm: 5,
    ft_pct: 0.8,
    fta: 5,
    ftm: 4,
    game: {
      id: 709,
      date: "1990-11-14T00:00:00.000Z",
      home_team_id: 23,
      home_team_score: 112,
      period: 4,
      postseason: false,
      season: 1990,
      status: "Final",
      time: " ",
      visitor_team_id: 1,
      visitor_team_score: 104,
    },
    min: "35",
    oreb: 1,
    pf: 4,
    player: {
      id: 565,
      first_name: "John",
      height_feet: null,
      height_inches: null,
      last_name: "Battle",
      position: "",
      team_id: 1,
      weight_pounds: null,
    },
    pts: 15,
    reb: 2,
    stl: 1,
    team: {
      id: 1,
      abbreviation: "ATL",
      city: "Atlanta",
      conference: "East",
      division: "Southeast",
      full_name: "Atlanta Hawks",
      name: "Hawks",
    },
    turnover: 2,
  },
  {
    id: 17798,
    ast: 6,
    blk: 0,
    dreb: 2,
    fg3_pct: null,
    fg3a: 0,
    fg3m: 0,
    fg_pct: 0.476,
    fga: 21,
    fgm: 10,
    ft_pct: 1,
    fta: 5,
    ftm: 5,
    game: {
      id: 723,
      date: "1990-11-16T00:00:00.000Z",
      home_team_id: 1,
      home_team_score: 109,
      period: 4,
      postseason: false,
      season: 1990,
      status: "Final",
      time: " ",
      visitor_team_id: 4,
      visitor_team_score: 119,
    },
    min: "38",
    oreb: 3,
    pf: 1,
    player: {
      id: 565,
      first_name: "John",
      height_feet: null,
      height_inches: null,
      last_name: "Battle",
      position: "",
      team_id: 1,
      weight_pounds: null,
    },
    pts: 25,
    reb: 5,
    stl: 3,
    team: {
      id: 1,
      abbreviation: "ATL",
      city: "Atlanta",
      conference: "East",
      division: "Southeast",
      full_name: "Atlanta Hawks",
      name: "Hawks",
    },
    turnover: 2,
  },
  {
    id: 18085,
    ast: 4,
    blk: 0,
    dreb: 2,
    fg3_pct: null,
    fg3a: 0,
    fg3m: 0,
    fg_pct: 0.357,
    fga: 14,
    fgm: 5,
    ft_pct: 1,
    fta: 6,
    ftm: 6,
    game: {
      id: 733,
      date: "1990-11-17T00:00:00.000Z",
      home_team_id: 9,
      home_team_score: 91,
      period: 4,
      postseason: false,
      season: 1990,
      status: "Final",
      time: " ",
      visitor_team_id: 1,
      visitor_team_score: 83,
    },
    min: "32",
    oreb: 0,
    pf: 1,
    player: {
      id: 565,
      first_name: "John",
      height_feet: null,
      height_inches: null,
      last_name: "Battle",
      position: "",
      team_id: 1,
      weight_pounds: null,
    },
    pts: 16,
    reb: 2,
    stl: 1,
    team: {
      id: 1,
      abbreviation: "ATL",
      city: "Atlanta",
      conference: "East",
      division: "Southeast",
      full_name: "Atlanta Hawks",
      name: "Hawks",
    },
    turnover: 2,
  },
  {
    id: 18349,
    ast: 4,
    blk: 0,
    dreb: 0,
    fg3_pct: 1,
    fg3a: 1,
    fg3m: 1,
    fg_pct: 0.5,
    fga: 10,
    fgm: 5,
    ft_pct: 0.5,
    fta: 4,
    ftm: 2,
    game: {
      id: 751,
      date: "1990-11-20T00:00:00.000Z",
      home_team_id: 4,
      home_team_score: 128,
      period: 4,
      postseason: false,
      season: 1990,
      status: "Final",
      time: " ",
      visitor_team_id: 1,
      visitor_team_score: 121,
    },
    min: "21",
    oreb: 2,
    pf: 2,
    player: {
      id: 565,
      first_name: "John",
      height_feet: null,
      height_inches: null,
      last_name: "Battle",
      position: "",
      team_id: 1,
      weight_pounds: null,
    },
    pts: 13,
    reb: 2,
    stl: 0,
    team: {
      id: 1,
      abbreviation: "ATL",
      city: "Atlanta",
      conference: "East",
      division: "Southeast",
      full_name: "Atlanta Hawks",
      name: "Hawks",
    },
    turnover: 2,
  },
];

const mockedPlayerStatsResponse = {
  data: [...mockedPlayerStats],
  meta: {
    total_pages: 67,
    current_page: 1,
    next_page: 2,
    per_page: 10,
    total_count: 667,
  },
};

describe("<PlayersStatsTable />", () => {
  beforeEach(() => {
    server.use(
      rest.get(`/stats`, (_, res, ctx) => {
        return res(ctx.json({ ...mockedPlayerStatsResponse }));
      })
    );

    render(<PlayersStatsTable playerId={mockedPlayerId} />);
  });

  beforeAll(() => server.listen());
  afterEach(() => server.resetHandlers());
  afterAll(() => server.close());

  it("should render loading spinner initially and then player stats data and table headers", async () => {
    expect(screen.getByTestId("player-stats-table-loader")).toBeInTheDocument();

    await waitFor(() =>
      expect(
        screen.queryByTestId("player-stats-table-loader")
      ).not.toBeInTheDocument()
    );

    await waitFor(() => {
      expect(
        screen.getAllByText(mockedPlayerStats[0].team.full_name)[0]
      ).toBeInTheDocument();

      const headers = Object.keys(mockedPlayerStats[0]).filter((key) => {
        if (!["id", "player"].includes(key)) return key;
      });

      headers.forEach((header) => {
        expect(screen.getByText(header)).toBeInTheDocument();
      });
    });
  });

  it("should render pagination", async () => {
    expect(screen.getByTestId("player-stats-table-loader")).toBeInTheDocument();

    await waitFor(() =>
      expect(
        screen.queryByTestId("player-stats-table-loader")
      ).not.toBeInTheDocument()
    );

    await waitFor(() =>
      expect(
        screen.queryByTestId("table-pagination-player-stats-table")
      ).toBeInTheDocument()
    );
  });
});
